name: Control Runner

on:
  workflow_dispatch:

  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  trigger-repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Aetherlyn-Nyxara-12
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/YOUR_USERNAME/Aetherlyn-Nyxara-12/actions/workflows/scheduler.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Wait 5 seconds
        run: sleep 5

      - name: Trigger varelix-kyrion
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/YOUR_USERNAME/varelix-kyrion/actions/workflows/indscrape.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Wait 5 seconds
        run: sleep 5

      - name: Trigger Thalorae-BackLioraen
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/YOUR_USERNAME/Thalorae-BackLioraen/actions/workflows/SolvynRun.yml/dispatches \
            -d '{"ref":"main"}'
